version: '3'
services:
  filer:
    image: udaystates9466/w3filter
    ports: 
      - "8001:80"
  signup:
    image: udaystates9466/w3signup
    ports:
      - "8002:80"
  checkout:
    image: udaystates9466/w3checkout
    ports:
      - "8003:80"
  social:
    image: udaystates9466/w3social
    ports: 
      - "8004:80"



